import type { Metadata } from "next";
import { Kosugi_Maru, Kaisei_Decol, Alumni_Sans } from "next/font/google";
import "./globals.css";

const alumniSans = Alumni_Sans({
  weight: "400",
  variable: "--font-alumni-sans",
  // display: "swap",
});

const kaiseiDecol = Kaisei_Decol({
  weight: "400",
  variable: "--font-kaisei-decol",
  // display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kaiseiDecol.variable} ${alumniSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
