"use client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { useState } from "react";
import type { Metadata } from "next";
import { Kaisei_Decol, Alumni_Sans } from "next/font/google";
import "./globals.css";
import { Background } from "@/comps/Background";

const alumniSans = Alumni_Sans({
  weight: "400",
  variable: "--font-alumni-sans",
  subsets: ["latin"],
  // display: "swap",
});

const kaiseiDecol = Kaisei_Decol({
  weight: "400",
  variable: "--font-kaisei-decol",
  subsets: ["latin"],
  // display: "swap",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [queryClient] = useState(
    () =>
      new QueryClient({
        defaultOptions: {
          queries: {
            staleTime: 60 * 1000, // 1分
            refetchOnWindowFocus: false,
          },
        },
      }),
  );

  return (
    <html lang="en">
      <body className={`${kaiseiDecol.variable} ${alumniSans.variable}`}>
        <Background>
          <QueryClientProvider client={queryClient}>
            {children}
          </QueryClientProvider>
        </Background>
      </body>
    </html>
  );
}
